version: "2"

services:
  app:
    image: golang:1.8-alpine
    volumes:
      - .:/go/src/min
    working_dir: /go/src/min
    command: go run main.go
    environment:
      - PORT=8080
    ports:
      - "80:8080"
